# Extension development environment
channels:
  - conda-forge
  - conda-forge/label/jupyterlab_beta

dependencies:
  # runtime dependencies
  - python >=3.10,<3.11.0a0
  - jupyterlab >=4.0.0b0,<5
  # labextension build dependencies
  - nodejs >=18,<19
  - pip
